before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then source ./travis/before-install_linux ; fi

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then source ./travis/install_linux ; fi

language: cpp

compiler:
  - gcc

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then source ./travis/script_linux ; fi

