# Import the environment configured in SConstruct
Import('env')

localenv = env.Clone()
localenv.Append(CPPPATH=['#/inc/sdlwrap'])
#Source files in this directory
sdlwrapobjs = [
    'render.cpp',
    'sdl.cpp',
    'surface.cpp',
    'window.cpp'
]

# Read child SConscript files and get their object files
for subdir in []:
    o = localenv.SConscript('%s/SConscript' % subdir, {'env': localenv})
    sdlwrapobjs.append(o)

sdlwraplib = localenv.StaticLibrary('sdlwrap', sdlwrapobjs)

Return('sdlwraplib')
