# Import the environment configured in SConstruct
Import('env')

objects = env.Object(['app.cpp', 'world.cpp'])
for subdir in ['input','logging', 'loop', 'management', 'render']:
    o = env.SConscript('%s/SConscript' % subdir, {'env': env})
    objects.extend(o)

#env.Library('core', objs)
Return('objects')
