# Import the environment configured in SConstruct
Import('env')

objects = []
for subdir in ['input','logging', 'loop', 'management', 'render']:
    o = env.SConscript('%s/SConscript' % subdir, {'env': env})
    objects.append(o)
#env.Library('core', objs)
Return('objects')
