# Import the environment configured in SConstruct
Import('env')

localenv = env.Clone()

#Source files in this directory
engineobjects = ['main.cpp']

# Read child SConscript files and get their object files
for subdir in []:
    o = localenv.SConscript('%s/SConscript' % subdir, {'env': localenv})
    engineobjects.append(o)

engineLibs = [
    'SDL2',
    'SDL2_image',
    'entityx']

# Executable Binaries
engine = localenv.Program('engine', engineobjects, LIBS=engineLibs)

# 'src' isn't very descriptive
env.Alias('engine', engine)
