# Import the environment configured in SConstruct
Import('env')

localenv = env.Clone()

#Source files in this directory
engineobjects = ['main.cpp']

# Read child SConscript files and get their object files
for subdir in ['core', 'samples']:
    o = localenv.SConscript('%s/SConscript' % subdir, {'env': localenv})
    engineobjects.append(o)

engineLibs = [
    'log4cplus',
    'SDL2',
    'SDL2_image'
    ]

# Executable Binaries
engine = localenv.Program('engine', engineobjects, LIBS=engineLibs, LIBPATH='.')

# 'src' isn't very descriptive
env.Alias('engine', engine)
